### PR TITLE
Change "EnforcedStyle: rails" to "EnforcedStyle: indented_internal_methods"

### PR DESCRIPTION
**Pull request by grimmxsleeper**
as per rubocop 0.72

### CODE REVIEW

**Comment by grimmxsleeper** [comment]
@toshimaru can you please take a look and merge, or address this some other way, this is blocking things for my team. Thanks.

**Comment by gt6089** [comment]
+1 to get this addressed, thanks.

**Comment by toshimaru** [comment]
The official rubocop.yml isn't updated yet. Please wait until it's updated.

https://github.com/rails/rails/blob/182d4751974cc95fb0145ea24299fd0ab98fd049/.rubocop.yml#L92-L94

**Comment by gnomus** [comment]
https://github.com/rails/rails/issues/36584

It doesn't seem that rails will change this anytime soon.
Could we lock rubocop to 0.71 for the time being?

**Comment by toshimaru** [comment]
> Could we lock rubocop to 0.71 for the time being?

Sure, PR is welcome. 👍

**Comment by koic** [comment]
https://github.com/rails/rails/pull/36943 has been merged.

**Comment by toshimaru** [comment]
`rubocop-rails_config` v0.7 has been released which includes this change. 🚀

**Pull request merged**
