### PR TITLE
Enable `Layout/SpaceAroundOperators` cop

### PR DESCRIPTION
**Pull request by koic**
Follow https://github.com/rails/rails/pull/40436.

This PR enables `Layout/SpaceAroundOperators` cop.
https://github.com/rails/rails/pull/40436 setting requires RuboCop 1.0 and RuboCop AST 1.0.1 or higher.
https://github.com/rubocop-hq/rubocop/issues/8919

Therefore this PR will be dropping versions that is lack for that requires.

### CODE REVIEW

**Comment by koic** [comment]
@toshimaru I think rubycop-rails_config can be released 1.0 after merging this PR.
cf: https://github.com/toshimaru/rubocop-rails_config/issues/71

**Comment by toshimaru** [comment]
@koic That's what I'm exactly thinking.
Also I'm considering dropping Ruby 2.4, which is EOL-ed, on v1.0.0 release. What do you think ❓

**Comment by koic** [comment]
Good point. RuboCop core still supports Ruby 2.4. So, I think we can support Ruby 2.4 if the maintenance cost is not high.
https://docs.rubocop.org/rubocop/1.0/compatibility.html#support-matrix

**Comment by toshimaru** [comment]
> To give people extra time for a smooth transition, we’ve customarily provided support for about one year after EOL of MRI version. This means that if Ruby 2.4 reaches its EOL in Spring 2020, it would be supported by RuboCop (at least) until Spring 2021.

https://docs.rubocop.org/rubocop/1.0/compatibility.html#support-matrix

Okay, rubocop still supports Ruby 2.4 until Spring 2021.

> I think we can support Ruby 2.4 if the maintenance cost is not high.

Personally, I was thinking it'd be better to drop Ruby 2.4, 
but as you said, the maintenance cost is not so high, so I keep it as is. 👍

**Review by toshimaru — APPROVED** [review]

**Pull request merged**
