### PR TITLE
Enable `Performance/UnfreezeString` cop

### PR DESCRIPTION
**Pull request by koic**
Refer rails/rails#32971.

### CODE REVIEW

**Comment by koic** [comment]
@toshimaru Please release at your good timing 😃

**Comment by toshimaru** [comment]
Hey, @koic, I have a question.

Unary plus operator is introduced in Ruby 2.3 and rubocop-rails_config gem requires Ruby 2.2+. How does [Performance/UnfreezeString cop](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Performance/UnfreezeString) work if I use Ruby 2.2?

**Comment by koic** [comment]
@toshimaru Yep. `Performance/UnfreezeString` cop is targeting Ruby 2.3 or higher.
https://github.com/rubocop-hq/rubocop/blob/v0.59.2/lib/rubocop/cop/performance/unfreeze_string.rb#L29

And since RubyCop supports Ruby 2.2 or higher.
https://github.com/rubocop-hq/rubocop/blob/v0.59.2/rubocop.gemspec#L12

So there is no problem.

**Comment by toshimaru** [comment]
> Performance/UnfreezeString cop is targeting Ruby 2.3 or higher.
https://github.com/rubocop-hq/rubocop/blob/v0.59.2/lib/rubocop/cop/performance/unfreeze_string.rb#L29

That's good to know, thanks. 

[v0.2.4](https://github.com/toshimaru/rubocop-rails_config/releases/tag/v0.2.4) has been released. ✌️

**Comment by koic** [comment]
Thanks 🚀

**Pull request merged**
